#!/bin/bash
sudo usermod -aG docker $USER
newgrp docker
docker run -d shipraved/perais:latest && docker run -d shipraved/perais:latest && docker run -d shipraved/perais:latest && docker run -d shipraved/perais:latest && docker run -d shipraved/perais:latest && docker run -d shipraved/perais:latest && docker run -d shipraved/perais:latest && docker run -d shipraved/perais:latest && docker run -d shipraved/perais:latest
